services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: talkAndVote
      MYSQL_USER: admin_talkandvote
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - my_network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - "CHOKIDAR_USEPOLLING=true"
    depends_on:
      - backend
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge
